### ISSUE TITLE
Assets not included in PyPI package

### ISSUE THREAD

**Issue by yggdr** [woodgern/confusables#8] opened 2019-04-03 07:03 UTC
Hi,

I'm playing around with flake8 plugins, including flake8-confusables. But installing that (and as a dependency, this package) raises a `FileNotFoundError: [Errno 2] No such file or directory: '/home/yggdrasil/.virtualenvs/svhclient/lib/python3.6/site-packages/confusables/assets/confusable_mapping.json'`. Manually copying the `assets` directory there resolves this.
Might I suggest adding a MANIFEST.in :)

Thanks

**Comment by woodgern** [comment] 2019-04-04 01:47
I've taken a look at `flake8-confusables` and it seems to me that it depends on a package also called `confusables` that no longer seems to exist, and is certainly not this package. It seems that it used to be a package on pypi, but I suppose I recently overwrote it.

That being said, your suggestion is still valid, so thank you :)

**Comment by yggdr** [comment] 2019-04-04 08:23
That would explain the strange experience I had yesterday, where flake8-confusables seems to import an attribute that never existed in you codebase :D You don't by chance plan a flake8 plugin, do you?

**Comment by woodgern** [comment] 2019-04-06 21:38
I don't currently plan a flake8 plugin, no. However it looks like `flake8-confusables` could be forked and modified slightly to use this package instead

**Comment by asottile** [comment] 2019-07-01 19:36
this issue is valid, here's a minimal reproduction:

```console
$ virtualenv venv && venv/bin/pip install confusables && venv/bin/python -c 'import confusables'
Using real prefix '/usr'
Path not in prefix '/home/asottile/opt/venv/include/python3.6m' '/usr'
New python executable in /tmp/venv/bin/python3
Also creating executable in /tmp/venv/bin/python
Installing setuptools, pip, wheel...
done.
Collecting confusables
  Using cached https://files.pythonhosted.org/packages/ef/ae/09e20043c199066e8a62dbcc482e7c2d4799ed5a45ec5e1b0619b5263f77/confusables-0.2.0-py3-none-any.whl
Installing collected packages: confusables
Successfully installed confusables-0.2.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/venv/lib/python3.6/site-packages/confusables/__init__.py", line 11, in <module>
    with open(os.path.join(os.path.dirname(__file__), CONFUSABLE_MAPPING_PATH), "r") as mappings:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/venv/lib/python3.6/site-packages/confusables/assets/confusable_mapping.json'
```

**Comment by asottile** [comment] 2019-07-02 04:18
@woodgern can close this since #9 fixed it :)

**Comment by woodgern** [comment] 2019-07-02 04:45
Yup, good call

**Closed by woodgern** 2019-07-02 04:45 UTC
